export { LoginComponent, EmailDialog } from './authorization/login/login.component';
export { RegisterComponent } from './authorization/register/register.component';
export { AuthorizationComponent } from './authorization/authorization.component';
export { DashboardComponent } from './dashboard/dashboard.component';
export { MusicComponent } from './dashboard/music/music.component';
export { ProfileComponent } from './dashboard/profile/profile.component';
export { CartComponent } from './dashboard/cart/cart.component';
export { TrackComponent } from './dashboard/music/track/track.component';
export { PlayerComponent } from './dashboard/player/player.component';
export { CartTrackComponent } from './dashboard/cart/cart-track/cart-track.component';
export { InfoComponent } from './dashboard/music/track/info/info.component';
export { AdminPanelComponent } from './dashboard/admin-panel/admin-panel.component';
export { UserComponent } from './dashboard/admin-panel/user/user.component';